[2024-04-17T22:27:58.934+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T22:27:58.968+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagExtract.extractApi scheduled__2024-04-17T20:30:00+00:00 [queued]>
[2024-04-17T22:27:58.978+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagExtract.extractApi scheduled__2024-04-17T20:30:00+00:00 [queued]>
[2024-04-17T22:27:58.979+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-17T22:27:58.998+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extractApi> on 2024-04-17 20:30:00+00:00
[2024-04-17T22:27:59.007+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=163) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T22:27:59.009+0000] {standard_task_runner.py:63} INFO - Started process 165 to run task
[2024-04-17T22:27:59.013+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagExtract', 'extractApi', 'scheduled__2024-04-17T20:30:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmp5yazlbwd']
[2024-04-17T22:27:59.020+0000] {standard_task_runner.py:91} INFO - Job 111: Subtask extractApi
[2024-04-17T22:27:59.095+0000] {task_command.py:426} INFO - Running <TaskInstance: dagExtract.extractApi scheduled__2024-04-17T20:30:00+00:00 [running]> on host 0761b779d565
[2024-04-17T22:27:59.256+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagExtract' AIRFLOW_CTX_TASK_ID='extractApi' AIRFLOW_CTX_EXECUTION_DATE='2024-04-17T20:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-17T20:30:00+00:00'
[2024-04-17T22:27:59.259+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T22:27:59.260+0000] {logging_mixin.py:188} INFO - Requesto to: https://api.openbrewerydb.org/breweries
[2024-04-17T22:27:59.261+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T22:27:59.262+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FirstDag.py", line 16, in ExtractApi
    response = requests.get(url)
               ^^^^^^^^
NameError: name 'requests' is not defined
[2024-04-17T22:27:59.285+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dagExtract, task_id=extractApi, execution_date=20240417T203000, start_date=20240417T222758, end_date=20240417T222759
[2024-04-17T22:27:59.310+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 111 for task extractApi (name 'requests' is not defined; 165)
[2024-04-17T22:27:59.346+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-17T22:27:59.394+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-17T22:27:59.404+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
