[2024-04-17T04:32:19.877+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T04:32:19.904+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-17T03:30:00+00:00 [queued]>
[2024-04-17T04:32:19.914+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-17T03:30:00+00:00 [queued]>
[2024-04-17T04:32:19.915+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-17T04:32:19.937+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): validateData> on 2024-04-17 03:30:00+00:00
[2024-04-17T04:32:19.946+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T04:32:19.948+0000] {standard_task_runner.py:63} INFO - Started process 75 to run task
[2024-04-17T04:32:19.948+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagExtract', 'validateData', 'scheduled__2024-04-17T03:30:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmpq__w33lt']
[2024-04-17T04:32:19.950+0000] {standard_task_runner.py:91} INFO - Job 104: Subtask validateData
[2024-04-17T04:32:20.020+0000] {task_command.py:426} INFO - Running <TaskInstance: dagExtract.validateData scheduled__2024-04-17T03:30:00+00:00 [running]> on host 5658728e6dbd
[2024-04-17T04:32:20.157+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagExtract' AIRFLOW_CTX_TASK_ID='validateData' AIRFLOW_CTX_EXECUTION_DATE='2024-04-17T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-17T03:30:00+00:00'
[2024-04-17T04:32:20.159+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T04:32:20.160+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-17T04:32:20.252+0000] {logging_mixin.py:188} INFO - Df Rows: 50
[2024-04-17T04:32:20.253+0000] {python.py:237} INFO - Done. Returned value was: persistData
[2024-04-17T04:32:20.253+0000] {branch.py:36} INFO - Branch into persistData
[2024-04-17T04:32:20.254+0000] {skipmixin.py:178} INFO - Following branch persistData
[2024-04-17T04:32:20.271+0000] {skipmixin.py:246} INFO - Skipping tasks [('exceptionData', -1)]
[2024-04-17T04:32:20.423+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T04:32:20.459+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dagExtract, task_id=validateData, execution_date=20240417T033000, start_date=20240417T043219, end_date=20240417T043220
[2024-04-17T04:32:20.525+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-17T04:32:20.572+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-17T04:32:20.578+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
