[2024-04-17T22:30:05.518+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T22:30:05.542+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-17T21:30:00+00:00 [queued]>
[2024-04-17T22:30:05.551+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-17T21:30:00+00:00 [queued]>
[2024-04-17T22:30:05.553+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-17T22:30:05.571+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): validateData> on 2024-04-17 21:30:00+00:00
[2024-04-17T22:30:05.579+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=240) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T22:30:05.581+0000] {standard_task_runner.py:63} INFO - Started process 242 to run task
[2024-04-17T22:30:05.585+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagExtract', 'validateData', 'scheduled__2024-04-17T21:30:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmpb0u25sni']
[2024-04-17T22:30:05.588+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask validateData
[2024-04-17T22:30:05.655+0000] {task_command.py:426} INFO - Running <TaskInstance: dagExtract.validateData scheduled__2024-04-17T21:30:00+00:00 [running]> on host 0761b779d565
[2024-04-17T22:30:05.786+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagExtract' AIRFLOW_CTX_TASK_ID='validateData' AIRFLOW_CTX_EXECUTION_DATE='2024-04-17T21:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-17T21:30:00+00:00'
[2024-04-17T22:30:05.789+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T22:30:05.790+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-17T22:30:05.868+0000] {logging_mixin.py:188} INFO - Df Rows: 50
[2024-04-17T22:30:05.869+0000] {python.py:237} INFO - Done. Returned value was: persistData
[2024-04-17T22:30:05.869+0000] {branch.py:36} INFO - Branch into persistData
[2024-04-17T22:30:05.870+0000] {skipmixin.py:178} INFO - Following branch persistData
[2024-04-17T22:30:05.895+0000] {skipmixin.py:246} INFO - Skipping tasks [('exceptionData', -1)]
[2024-04-17T22:30:05.933+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T22:30:05.967+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dagExtract, task_id=validateData, execution_date=20240417T213000, start_date=20240417T223005, end_date=20240417T223005
[2024-04-17T22:30:05.998+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-17T22:30:06.041+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-17T22:30:06.047+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
